######################################################################
# Automatically generated by qmake (1.07a) Fri Mar 23 16:17:02 2012
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
